name: Test Python

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macOS-14]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.11"

      - name: Install RDP & dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest


  readme:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v5

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.11"

    - name: Install RDP & dependencies
      run: uv sync --group docs

    - name: Persist virtual environment
      # Each `run` is in a separate shell. Make the virtual env available across steps.
      run: |
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        path: README.qmd


  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: chartboost/ruff-action@v3
